# Generated by Django 3.1.3 on 2023-01-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='chocies',
            new_name='choices',
        ),
        migrations.AlterField(
            model_name='choice',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
